version: '3'
services:
  redis:
    image: redis:alpine
    networks:
      - redis-net
    expose:
      - 6379
    restart: always

  back:
    image: shubhamoy/backend_docker_app:latest
    restart: always
    networks:
      - redis-net
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  front:
    image: shubhamoy/frontend_docker_app:latest
    restart: always
    networks:
      - redis-net
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - 3000:3000

networks:
  redis-net: